import {Planet} from "./planet";
export const PLANETS: Planet[] =[
    {
        name: 'aas',
        position: null,
        star_system: null,
        sector: null,
        environment: null,
        sentient_species: null,
        atmosphere: null,
        gravity: null,
        diameter: null,
      },
      {
        name: 'Bbs',
        position: null,
        star_system: null,
        sector: null,
        environment: null,
        sentient_species: null,
        atmosphere: null,
        gravity: null,
        diameter: null,
      },
      {
        name: 'Ccss',
        position: null,
        star_system: null,
        sector: null,
        environment: null,
        sentient_species: null,
        atmosphere: null,
        gravity: null,
        diameter: null,
      },
      {
        name: 'Ccss',
        position: null,
        star_system: null,
        sector: null,
        environment: null,
        sentient_species: null,
        atmosphere: null,
        gravity: null,
        diameter: null,
      },
      {
        name: 'Ccss',
        position: null,
        star_system: null,
        sector: null,
        environment: null,
        sentient_species: null,
        atmosphere: null,
        gravity: null,
        diameter: null,
      },
      {
        name: 'Ccss',
        position: null,
        star_system: null,
        sector: null,
        environment: null,
        sentient_species: null,
        atmosphere: null,
        gravity: null,
        diameter: null,
      },
      {
        name: 'Ccss',
        position: null,
        star_system: null,
        sector: null,
        environment: null,
        sentient_species: null,
        atmosphere: null,
        gravity: null,
        diameter: null,
      },
      {
        name: 'Ccss',
        position: null,
        star_system: null,
        sector: null,
        environment: null,
        sentient_species: null,
        atmosphere: null,
        gravity: null,
        diameter: null,
      },
      {
        name: 'Ccss',
        position: null,
        star_system: null,
        sector: null,
        environment: null,
        sentient_species: null,
        atmosphere: null,
        gravity: null,
        diameter: null,
      }
    ];